llm:
  # Gemini
  gemini-2.5-pro:
    model: gemini-2.5-pro
    base_url: ${BASE_URL}
    api_key: ${API_KEY}

  gemini-2.5-flash:
    model: gemini-2.5-flash
    base_url: ${BASE_URL}
    api_key: ${API_KEY}

  gemini-2.5-flash-thinking:
    model: gemini-2.5-flash-thinking
    base_url: ${BASE_URL}
    api_key: ${API_KEY}

  # GPT
  gpt-4.1:
    model: gpt-4.1
    base_url: ${BASE_URL}
    api_key: ${API_KEY}

  gpt-5:
    model: gpt-5
    base_url: ${BASE_URL}
    api_key: ${API_KEY}

  gpt-5-mini:
    model: gpt-5-mini
    base_url: ${BASE_URL}
    api_key: ${API_KEY}

  o4-mini:
    model: o4-mini
    base_url: ${BASE_URL}
    api_key: ${API_KEY}

  # Deepseek
  deepseek-v3:
    model: USD-guiji/deepseek-v3
    base_url: ${BASE_URL}
    api_key: ${API_KEY}

  deepseek-r1:
    model: USD-guiji/deepseek-r1
    base_url: ${BASE_URL}
    api_key: ${API_KEY}

  # Claude
  claude-thinking:
    model: claude-opus-4-20250514-thinking
    base_url: ${BASE_URL}
    api_key: ${API_KEY}

  claude:
    model: claude-3-7-sonnet-20250219
    base_url: ${BASE_URL}
    api_key: ${API_KEY}

  claude-3-5-haiku-latest:
    model: claude-3-5-haiku-latest
    base_url: ${BASE_URL}
    api_key: ${API_KEY}

  # Qwen
  Qwen3-235B-A22B:
    model: Qwen/Qwen3-235B-A22B
    base_url: ${BASE_URL}
    api_key: ${API_KEY}

  Qwen3-32B:
    model: Qwen/Qwen3-32B
    base_url: ${BASE_URL}
    api_key: ${API_KEY}
